"""API endpoints for incrementally tailing logs."""
# src/pinballctl/app/modules/logs/api.py

from flask import Blueprint, jsonify, request, abort, send_file
import os, re
from pathlib import Path  # needed for _read_incremental typing
from collections import deque
from pinballctl.log_maintenance import (
    list_archives as _list_archives,
    maintain_logs_once,
    resolve_archive as _resolve_archive,
)

# 👇 MUST exist before any @api_bp.get(...) usage
api_bp = Blueprint("logs_api", __name__)

# ------- config / defaults ----------------------------------------------------
try:
    MAX_BYTES_PER_READ
except NameError:
    MAX_BYTES_PER_READ = 2 * 1024 * 1024
try:
    DEFAULT_LINES
except NameError:
    DEFAULT_LINES = 500

# ------- helper fallbacks (defined only if missing) --------------------------
try:
    _state_dir
except NameError:
    def _state_dir() -> Path:
        """Return the state directory used by pinballctl logs."""
        return Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local" / "state")) / "pinballctl"

try:
    _stat
except NameError:
    def _stat(fp: Path):
        """Return a small stat dict for the given path."""
        s = fp.stat()
        return {"size": s.st_size, "inode": getattr(s, "st_ino", None), "mtime": int(s.st_mtime)}

try:
    _tail_last_lines
except NameError:
    def _tail_last_lines(fp: Path, lines=DEFAULT_LINES, max_bytes=MAX_BYTES_PER_READ):
        """Read last N lines without loading the entire file into memory."""
        try:
            with fp.open("rb") as f:
                f.seek(0, os.SEEK_END)
                size = f.tell()
                block = bytearray()
                line_count = 0
                step = 4096
                pos = size
                while pos > 0 and len(block) < max_bytes and line_count <= lines:
                    read = min(step, pos)
                    pos -= read
                    f.seek(pos)
                    block[:0] = f.read(read)  # prepend
                    line_count = block.count(b"\n")
                data = block.splitlines()[-lines:]
                text = b"\n".join(data).decode("utf-8", "replace")
                return text, size
        except Exception:
            return "", 0

def _resolve_single_log_path(target: str) -> Path:
    """Map a logical target string to its log path."""
    s = _state_dir()
    if target == "bridge":
        return s / "bridge.log"
    if target == "espraw":
        return s / "esp-raw.log"
    if target == "events":
        return s / "events.log"
    if target == "error":
        return s / "gunicorn-error.log"
    if target == "access":
        return s / "gunicorn-access.log"
    # default fallback -> error
    return s / "gunicorn-error.log"


def _normalize_target(target: str) -> str:
    t = (target or "").strip().lower()
    # Backward compatibility: old clients may send "web".
    if t == "web":
        return "error"
    if t in {"bridge", "espraw", "events", "error", "access"}:
        return t
    return "error"

@api_bp.post("/purge")
def purge_log():
    """Delete the selected log file."""
    target = request.args.get("target", "error")
    target = _normalize_target(target)
    fp = _resolve_single_log_path(target)
    try:
        if fp.exists():
            with fp.open("w", encoding="utf-8") as f:
                f.truncate(0)
        return jsonify({"ok": True})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)}), 400


@api_bp.get("/archives")
def list_archives():
    """Return historical archives for a given source target."""
    target = _normalize_target(request.args.get("target", "error"))
    try:
        limit = int(request.args.get("limit", "200"))
    except Exception:
        limit = 200
    archives = _list_archives(target, limit=max(1, min(1000, limit)))
    return jsonify({"ok": True, "target": target, "archives": archives})


@api_bp.get("/download")
def download_log():
    """Download the selected current log file or archive."""
    target = _normalize_target(request.args.get("target", "error"))
    archive_name = (request.args.get("archive") or "").strip()
    if archive_name:
        path = _resolve_archive(target, archive_name)
        if path is None:
            abort(404)
        download_name = path.name
    else:
        path = _resolve_single_log_path(target)
        if not path.exists() or not path.is_file():
            abort(404)
        download_name = path.name
    return send_file(path, as_attachment=True, download_name=download_name, mimetype="text/plain")

# ------- access-log suppression ----------------------------------------------
ACCESS_RE_INTERNAL = re.compile(r'"\s*(GET|POST|PUT|DELETE|OPTIONS)\s+/logs/', re.IGNORECASE)

def _suppress_internal_lines(text: str, enabled: bool) -> str:
    """Filter access log lines generated by the logs endpoint itself."""
    if not enabled or not text:
        return text
    trailing_newline = text.endswith("\n") or text.endswith("\r\n")
    out = []
    for ln in text.splitlines():
        if ACCESS_RE_INTERNAL.search(ln):
            continue
        out.append(ln)
    result = "\n".join(out)
    if trailing_newline and result:
        result += "\n"
    return result

# ------- incremental read helper ---------------------------------------------
def _read_incremental(fp: Path, offset: int, cap: int):
    """Read from a file starting at offset with a maximum byte cap."""
    st = _stat(fp)
    if st["size"] < offset:  # rotated/truncated
        txt, _ = _tail_last_lines(fp, lines=DEFAULT_LINES, max_bytes=cap)
        st2 = _stat(fp)
        return txt, st2, True, st2["size"]
    to_read = min(cap, st["size"] - offset)
    data = b""
    with fp.open("rb") as f:
        f.seek(offset)
        if to_read > 0:
            data = f.read(to_read)
    txt = data.decode("utf-8", "replace")
    st2 = _stat(fp)
    return txt, st2, False, min(offset + len(data), st2["size"])

# ------- main chunk endpoint --------------------------------------------------
@api_bp.get("/chunk")
def logs_chunk():
    """Return incremental or tail-backfill chunks for a single log target."""
    target = _normalize_target(request.args.get("target", "error"))
    archive_name = (request.args.get("archive") or "").strip()
    suppress_internal = (request.args.get("suppress_internal", "1") != "0")
    try:
        maintain_logs_once(throttle_s=15.0)
    except Exception:
        pass

    # shared inputs
    try:
        cap_req = int(request.args.get("max_bytes", 0))
    except Exception:
        cap_req = 0
    cap = min(MAX_BYTES_PER_READ, cap_req) if cap_req > 0 else MAX_BYTES_PER_READ

    try:
        lines = max(0, int(request.args.get("lines", DEFAULT_LINES)))
    except Exception:
        lines = DEFAULT_LINES

    keyword = (request.args.get("filter") or "").strip().lower()

    def _filter_text(text: str, kw: str) -> str:
        if not kw:
            return text
        trailing_newline = text.endswith("\n") or text.endswith("\r\n")
        result = "\n".join([ln for ln in text.splitlines() if kw in ln.lower()])
        if trailing_newline and result:
            result += "\n"
        return result

    # ----- single-file mode -----------------------------------------
    if archive_name:
        path = _resolve_archive(target, archive_name)
        if path is None:
            return jsonify({"data": "", "next_offset": 0, "stat": {}, "rotated": False, "archive": archive_name}), 404
    else:
        path = _resolve_single_log_path(target)
    if not path.exists():
        return jsonify({"data": "", "next_offset": 0, "stat": {}, "rotated": False}), 200

    try:
        offset = int(request.args.get("offset", "0"))
        if offset < 0:
            offset = 0
    except Exception:
        offset = 0

    st = _stat(path)

    # initial backfill (current logs only)
    if offset == 0 and not archive_name:
        text, _ = _tail_last_lines(path, lines=lines, max_bytes=cap)
        st = _stat(path)
        text = _suppress_internal_lines(text, suppress_internal)
        text = _filter_text(text, keyword)
        return jsonify({
            "data": text,
            "next_offset": st["size"],
            "stat": st,
            "rotated": False
        })

    # incremental
    text, st2, rotated, next_offset = _read_incremental(path, offset, cap)
    text = _suppress_internal_lines(text, suppress_internal)
    text = _filter_text(text, keyword)
    return jsonify({
        "data": text,
        "next_offset": next_offset,
        "stat": st2,
        "rotated": rotated
    })
